spring:
  application:
    name: cupcakeapi
  profiles:
    default: "local"

management:
  endpoints:
    web:
      exposure:
        include: info, health

cupcakeapi:
  security:
    token:
      secret: ${JWT_SECRET:myreallysecurejwtsecret}
      issuer: API Cupcakeapi